CREATE table person(
    id          int generated by default as identity primary key,
    first_name  varchar(20)    not null,
    second_name varchar(20)    not null,
    phone       varchar(13)    not null unique,
    email       varchar unique not null
);
CREATE table address(
    id int generated by default as identity primary key ,
    city varchar(20) not null ,
    street varchar(20) not null ,
    house int,
    letter varchar(1) default '',
    entrance int,
    apartment int,
    owner_id int references person(id)
);
CREATE table meter(
    id int generated by default as identity primary key ,
    number int not null unique ,
    indexes int,
    date TIMESTAMP default CURRENT_DATE,
    address_id int references address(id)
);
CREATE table index(
    id int generated by default as identity primary key ,
    index int,
    date TIMESTAMP default CURRENT_TIMESTAMP,
    meter_id int references meter(id)
);
DROP table index;
DROP table meter;
DROP table address;
DROP table person;